In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import warnings
warnings.filterwarnings('ignore')

In [31]:
#loading the dataset to a pandas DataFrame
credit_card_data = pd.read_csv('creditcard.csv')

In [32]:
credit_card_data.head()

   Time        V1        V2        V3  ...       V27       V28  Amount  Class
0     0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62    0.0
1     0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69    0.0
2     1 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66    0.0
3     1 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50    0.0
4     2 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99    0.0

[5 rows x 31 columns]

In [33]:
credit_card_data.tail()

        Time        V1        V2        V3  ...       V27       V28  Amount  Class
19893  30631 -0.377215  0.973528  1.647077  ...  0.056522  0.033139   29.90    0.0
19894  30631  1.209281  0.078793  0.061820  ... -0.025292  0.021130   16.00    0.0
19895  30632  1.286596 -1.450336  0.814530  ...  0.026395  0.030885   92.00    0.0
19896  30633 -0.488090  1.018448  0.670593  ...  0.130266  0.067290    1.99    0.0
19897  30633 -2.609841  2.479357  0.763844  ...       NaN       NaN     NaN    NaN

[5 rows x 31 columns]

In [34]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19898 entries, 0 to 19897
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    19898 non-null  int64
 1   V1      19898 non-null  float64
 2   V2      19898 non-null  float64
 3   V3      19898 non-null  float64
 4   V4      19898 non-null  float64
 5   V5      19898 non-null  float64
 6   V6      19898 non-null  float64
 7   V7      19898 non-null  float64
 8   V8      19898 non-null  float64
 9   V9      19898 non-null  float64
 10  V10     19898 non-null  float64
 11  V11     19897 non-null  float64
 12  V12     19897 non-null  float64
 13  V13     19897 non-null  float64
 14  V14     19897 non-null  float64
 15  V15     19897 non-null  float64
 16  V16     19897 non-null  float64
 17  V17     19897 non-null  float64
 18  V18     19897 non-null  float64
 19  V19     19897 non-null  float64
 20  V20     19897 non-null  float64
 21  V21     19897 non-null  float64
 22  V22     19897 non-null  float64
 23  V23     19897 non-null  float64
 24  V24     19897 non-null  float64
 25  V25     19897 non-null  float64
 26  V26     19897 non-null  float64
 27  V27     19897 non-null  float64
 28  V28     19897 non-null  float64
 29  Amount  19897 non-null  float64
 30  Class   19897 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 4.7 MB

In [35]:
#checking the missing values
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       1
V12       1
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [36]:
#distribution of legit transaction & fraudulent transaction
credit_card_data['Class'].value_counts()

Class
0.0    19812
1.0       85
Name: count, dtype: int64

This Dataset is highly unbalanced

0 ---> Normal Transaction

1 ---> Fraudulent Transaction

In [37]:
#separating the data analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [38]:
print(legit.shape)
print(fraud.shape)

(19812, 31)
(85, 31)

In [39]:
#statistical measures of the data
legit.Amount.describe()

count    19812.000000
mean        70.169855
std        205.091118
min          0.000000
25%          5.900000
50%         16.070000
75%         59.950000
max       7879.420000
Name: Amount, dtype: float64

In [40]:
fraud.Amount.describe()

count      85.000000
mean       93.869647
std       261.736641
min         0.000000
25%         1.000000
50%         1.000000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [41]:
#compare the values for both transactions
credit_card_data.groupby('Class').mean()

               Time        V1        V2  ...       V27       V28     Amount
Class                                    ...
0.0    15483.312841 -0.207233  0.215159  ...  0.010624  0.006940  70.169855
1.0    17436.164706 -8.862174  6.570214  ...  0.907255  0.093985  93.869647

[2 rows x 30 columns]

Under-Sampling

Bulid a sample dataset containing similar distribution of normal transaction and fraudulent transaction

Number of Fraudulen Transection --> 85

In [42]:
legit_sample = legit.sample(n=85)

Concatenating two DataFrames

In [43]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [44]:
new_dataset.head()

        Time        V1        V2        V3  ...       V27       V28  Amount  Class
16914  28287  1.027159 -0.015806  1.478630  ...  0.057230  0.011973    0.00    0.0
16565  27930 -0.559457  0.788227  1.426590  ...  0.409840  0.196137   32.50    0.0
18870  29834 -1.168932  0.609764  0.431029  ...  0.427724  0.287431   75.00    0.0
2113    1627 -0.953611  1.447281  0.540884  ... -0.371882 -0.775072    1.23    0.0
13890  24652  0.740373 -0.011557 -0.020730  ... -0.084533  0.015273  189.64    0.0

[5 rows x 31 columns]

In [45]:
new_dataset.tail()

        Time         V1         V2  ...       V28  Amount  Class
17480  28755 -30.552380  16.713389  ...  0.356660   99.99    1.0
18466  29526   1.102804   2.829168  ...  0.153318    0.68    1.0
18472  29531  -1.060676   2.608579  ...  0.192177    0.68    1.0
18773  29753   0.269614   3.549755  ...  0.402400    0.68    1.0
18809  29785   0.923764   0.344048  ... -0.049729   30.30    1.0

[5 rows x 31 columns]

In [46]:
new_dataset['Class'].value_counts()

Class
0.0    85
1.0    85
Name: count, dtype: int64

In [47]:
new_dataset.groupby('Class').mean()

               Time        V1        V2  ...       V27       V28     Amount
Class                                    ...
0.0    16012.388235 -0.260549  0.428961  ...  0.042874  0.016168  60.481529
1.0    17436.164706 -8.862174  6.570214  ...  0.907255  0.093985  93.869647

[2 rows x 30 columns]

Splitting the data into Features & Targets

In [48]:
x = new_dataset.drop(columns='Class', axis=1)
y = new_dataset['Class']

In [49]:
print(x)

        Time         V1         V2  ...       V27       V28  Amount
16914  28287   1.027159  -0.015806  ...  0.057230  0.011973    0.00
16565  27930  -0.559457   0.788227  ...  0.409840  0.196137   32.50
18870  29834  -1.168932   0.609764  ...  0.427724  0.287431   75.00
2113    1627  -0.953611   1.447281  ... -0.371882 -0.775072    1.23
13890  24652   0.740373  -0.011557  ... -0.084533  0.015273  189.64
...      ...        ...        ...  ...       ...       ...     ...
17480  28755 -30.552380  16.713389  ...  1.232636  0.356660   99.99
18466  29526   1.102804   2.829168  ...  0.009146  0.153318    0.68
18472  29531  -1.060676   2.608579  ... -0.130918  0.192177    0.68
18773  29753   0.269614   3.549755  ...  0.553255  0.402400    0.68
18809  29785   0.923764   0.344048  ...  0.489035 -0.049729   30.30

[170 rows x 30 columns]

In [50]:
print(y)

16914    0.0
16565    0.0
18870    0.0
2113     0.0
13890    0.0
        ...
17480    1.0
18466    1.0
18472    1.0
18773    1.0
18809    1.0
Name: Class, Length: 170, dtype: float64

Split the data into Training data & Testing Data

In [51]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, stratify=y, random_state=2)

In [52]:
print(x.shape, x_train.shape, x_test.shape)

(170, 30) (136, 30) (34, 30)

Model Traning

Logistic Regression

In [53]:
model = LogisticRegression()

In [55]:
#Traning the logistic regression model
model.fit(x_train, y_train)

LogisticRegression()

Model Evalution

Accuracy Score

In [56]:
#accuracy on training data
x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction, y_train)

In [57]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9558823529411765

In [58]:
#accuracy on test data
x_test_prediction = model.predict(x_test)
test_data_accuracy = accuracy_score(x_test_prediction, y_test)

In [59]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9117647058823529